// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Virksomhedsgodkendelser.Data;

namespace Virksomhedsgodkendelser.Migrations
{
    [DbContext(typeof(VirksomhedsgodkendelserContext))]
    [Migration("20191113133750_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Virksomhedsgodkendelser.Models.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AntalIgangvarendeAftaler")
                        .HasColumnType("int");

                    b.Property<string>("COSAnr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CVRnr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GodkendelseOprettet")
                        .HasColumnType("datetime2");

                    b.Property<int>("Godkendelsesaendring")
                        .HasColumnType("int");

                    b.Property<int>("Godkendelsesantal")
                        .HasColumnType("int");

                    b.Property<DateTime>("Godkendelsesdato")
                        .HasColumnType("datetime2");

                    b.Property<int>("Nygodkendelse")
                        .HasColumnType("int");

                    b.Property<int>("Pnr")
                        .HasColumnType("int");

                    b.Property<string>("PostnrPostdistrikt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialekodeSpecialebetegnelse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tlfnr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UddannelseskodeUddannelsesbetegnelse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Virksomhedsnavn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Company");
                });
#pragma warning restore 612, 618
        }
    }
}
